umbrel/Dockerfile

Example usage: ` docker build --build-arg GIT_REPO=https://github.com/Kukks/helipad --build-arg GIT_BRANCH=explicit-config .`

Allow docker to build custom version

---

webroot/script/home.js

Regularly updates the relative time shown for each boost, and provides the ability to hover over a timestamp and see the absolute date/time of a boost. This also changes the HTML element from <span> to <time> which is more semantically correct.

Improve boost timestamp display

---

webroot/script/home.js

Restore proper boost app name casing on the img title attribute, and add the alt attribute to same. Also wrap the message body itself in its own div so that it isn't "free-floating" inside the overall message element.

Message template improvements

---

webroot/script/home.js

`boostApp` appears to already be properly cased, so we shouldn't make it lower-case to use on the img tag's title attribute. In addition, include the alt attribute as it is still accessibility best practice to always include that attribute on media elements.

improve boost app name display

---

webroot/script/home.js
webroot/script/streams.js

Added a new `shouldPew` param to `getBoosts()` which is set to true when polling the server and false for any user-triggered actions.
Resolves #45

Should only pew pew for new boosts received from the server

---

webroot/script/home.js
webroot/script/streams.js

Fixes an issue with my previous PR in which there would be no pew pew during your first boost.
This is due to the code polling `initPage()` when no boosts exist on the page, which in turn calls `getIndex()` which then calls `getBoosts()` with `shouldPew=false` to generate the nodata message. I've added an override to set `shouldPew=true` when the nodata message is being shown to ensure proper pew pews when receiving the first boost.

Should pew when receiving our first boost

---

src/main.rs

The current `std::thread::sleep` call seems to also put the HTTP server to sleep after each iteration of the LND poller. I've updated the call to use `tokio::time::sleep` instead, which lets the HTTP server continue running while the LND poller is sleeping.
Resolves #47

Use tokio::time::sleep to sleep the LND poller and not the HTTP server

---

webroot/html/home.html
webroot/html/streams.html
webroot/script/home.js
webroot/script/streams.js
webroot/script/utils.js
webroot/style/default.css

* Boosts and Streams links added to the top of the page to make it easy to switch between the two.
* Number formatting according to the browser's locale settings
* Actual sats received moved to mouse over
* Updated 'boosts' text to 'streams' on Streams page
Here's what the nav links, formatting, and mouse overs look like:
Here's the iPhone SE mobile view (as rendered by Brave):
Here's what the stream text looks like:

Added navigation links and misc UI tweaks

---

src/handler.rs
src/main.rs
webroot/extra/numerology.json
webroot/script/home.js
webroot/script/streams.js
webroot/style/default.css

This adds emojis for donation amounts with known numerology. The numerology itself is defined in a `numerology.json` file that could _theoretically_ be changed manually by whoever is running Helipad.
It uses BoostBot's numerology by default: https://github.com/valcanobacon/BoostBots . I know that some shows have developed their own numerology (Podnews: https://podnews.net/article/boostagram-numerology) and I wonder if I need to add a configuration page to allow the user to change or remove these numbers before this change gets deployed.
Here is what the interface looks like with this change:

Added numerology emojis to the interface

---

Cargo.toml
dbif/src/lib.rs
src/main.rs
webroot/script/home.js
webroot/script/streams.js

Uses the Podcastindex API to resolve remote item guids into actual podcast (feedTitle) and episode (title) names, show the names in parentheses in the interface, and store them in the Helipad DB.
I did notice that the feedTitle and title seem to be the same for most music tracks:
* https://api.podcastindex.org/api/1.0/value/byepisodeguid?podcastguid=b8b6971e-403e-568f-a4e6-7aa2b45e50d4&episodeguid=72a3b402-8491-4cd9-823e-a621fd81b86f
* https://api.podcastindex.org/api/1.0/value/byepisodeguid?podcastguid=78ae7a58-679a-50dd-95c0-c8f69e431b78&episodeguid=e1c2e15d-656c-41de-a52c-6771292a7312

Resolve remote items into podcast/episode names and show with boosts

---

webroot/script/home.js
webroot/script/streams.js

Clicking on the timestamp of a boost/stream will now show the entire TLV as a table within a modal:

Added modal to view the entire TLV record of a boost/stream

---

src/handler.rs
webroot/script/home.js
webroot/script/streams.js

* Adds links for remote podcast/episode boosts that link to  corresponding podcast pages on podcastindex.org.
Links to https://podcastindex.org/podcast/b8b6971e-403e-568f-a4e6-7aa2b45e50d4
* Adds `remote_podcast` and `remote_episode` fields to the CSV export
* Removes leading spaces from column names in CSV export

Link remote podcast/episodes to PI website and include in CSV

---

src/main.rs

The Podcast Index API now seems require a User-Agent header for API calls. This commit adds a `Helipad/version` header when calling the API.

Added missing User-Agent header when calling the Podcast Index API

---

dbif/src/lib.rs
src/lightning.rs
webroot/script/helipad.js

Shows a clock icon next to automated boosts. No action boosts are shown with whatever information is available:
Resolves #67 #71

Show automated boosts in the Boosts tab

---

dbif/src/lib.rs
src/handler.rs
src/main.rs
webroot/html/home.html
webroot/html/sent.html
webroot/html/streams.html
webroot/script/helipad.js
webroot/script/utils.js

Adds an additional option to the reply boost modal to select between Node and Browser (if a WebLN extension is installed). If Browser is selected, it enables the WebLN extension and sends the boost through it instead of the node.
Resolves #76

Added browser-based reply boosts (e.g. WebLN, Alby)

---

dbif/src/lib.rs
src/lightning.rs
webroot/script/helipad.js

* Removes fields from RawBoost that are not actually used by Helipad
* Include payments with invalid or missing actions into the Streams tab 
* Adds a Download TLV link to the Boost Info modal
* Show the TLV itself if the Boost Info modal can't parse it
Resolves #71

Improve strange TLV handling

---

dbif/src/lib.rs
src/handler.rs
src/main.rs
webroot/html/home.html
webroot/html/sent.html
webroot/html/settings.html
webroot/html/streams.html
webroot/script/helipad.js
webroot/style/default.css

Adds the ability to filter by a particular podcast (Resolves #74)
Adds a filter button to the top:
Clicking on the filter button reveals the filter options:
Clicking on Filter by podcast brings up a list of podcasts from the db:
To-do:

Add podcast filter

---

webroot/script/helipad.js

Fountain is now sending nostr references in boost messages. This PR adds links to njump.me for any nostr references it finds.
Resolves #97

Add njump links to nostr references

---

Cargo.toml
dbif/src/lib.rs
src/handler.rs
src/main.rs
webroot/html/settings.html

Adds a custom reports section to let users export boost, stream, and payment data for specific podcasts and timeranges and with USD conversions.

Add custom reports to settings page

---

src/handler.rs

Changes the date/time format to '%Y-%m-%d %H:%M:%S' with a separate timezone column. This seems to be recognized by Libreoffice Calc.
Resolves #119

Switch export date/time format to '%Y-%m-%d %H:%M:%S' with separate tz column
